# Generated by Django 5.2.8 on 2025-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryticket',
            name='admin_resolution',
            field=models.TextField(blank=True, help_text='The resolution/reply from the admin for the user to see.', null=True),
        ),
    ]
